apiVersion: apps/v1
kind: Deployment
metadata:
  name: oemer-depl
  namespace: ingress-nginx

spec:
  replicas: 1
  selector:
    matchLabels:
      app: oemer
  template:
    metadata:
      labels:
        app: oemer
    spec:
      containers:
        - name: oemer
          image: heysirius/oemer
