apiVersion: apps/v1
kind: Deployment
metadata:
  name: oemer-depl
  namespace: ingress-nginx

spec:
  replicas: 1
  selector:
    matchLabels:
      app: oemer
  template:
    metadata:
      labels:
        app: oemer
    spec:
      containers:
        - name: oemer
          image: heysirius/oemer
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: MONGO_URI
              value: mongodb://oemer-mongo-srv:27017/oemer
            - name: NATS_CLUSTER_ID
              value: 'oemer'
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
---
apiVersion: v1
kind: Service
metadata:
  name: oemer-srv
  namespace: ingress-nginx

spec:
  selector:
    app: oemer
  ports:
    - name: oemer
      protocol: TCP
      port: 3000
      targetPort: 3000
